server:
  port: 0
spring:
  application:
    name: notifications-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notifications-consumer
    producer:
      group-id: notifications-producer