apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: document-collaboration
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: roddevv/api-gateway
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 1
          env:
            - name: AUTH_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: services-map
                  key: auth
            - name: DOCUMENT_MANIPULATION_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: services-map
                  key: documents
            - name: NOTIFICATIONS_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: services-map
                  key: notifications
            - name: RTC_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: services-map
                  key: rtc
            - name: CONTENT_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: services-map
                  key: documents-content
          ports:
            - containerPort: 8080