apiVersion: apps/v1
kind: Deployment
metadata:
  name: documents
  namespace: document-collaboration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: documents
  template:
    metadata:
      labels:
        app: documents
    spec:
      containers:
        - name: document
          image: roddevv/document-manipulation
          env:
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: documents-db-config
                  key: host
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: documents-db-config
                  key: port
            - name: DB
              valueFrom:
                configMapKeyRef:
                  name: documents-db-config
                  key: db
            - name: AUTHENTICATION_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: documents-db-config
                  key: authentication-database
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: documents-db-secret
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: documents-db-secret
                  key: password
            - name: KAFKA
              valueFrom:
                configMapKeyRef:
                  name: services-map
                  key: kafka
          ports:
            - containerPort: 8080