apiVersion: v1
kind: Secret
metadata:
  name: user-db-secret
  namespace: document-collaboration
type: Opaque
data:
  username: cm9vdA==
  password: cm9vdA==
  secret-key: "NDA0RTYzNTI2NjU1NkE1ODZFMzI3MjM1NzUzODc4MkY0MTNGNDQyODQ3MkI0QjYyNTA2NDUzNjc1NjZCNTk3MAoa"
