spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: auth
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
        - id: document-manipulation
          uri: lb://DOCUMENT-MANIPULATION-SERVICE
          filters:
            - AuthGatewayFilter
          predicates:
            - Path=/document/**
        - id: notifications
          uri: lb://NOTIFICATIONS-SERVICE
          filters:
            - AuthGatewayFilter
          predicates:
            - Path=/notifications/**
        - id: users
          uri: lb://USERS-SERVICE
          filters:
            - AuthGatewayFilter
          predicates:
            - Path=/users/**
server:
  port: 8080

cloud:
  gateway:
    globalcors:
      corsConfigurations:
        '[/**]':
          allowedOrigins: "https://docs.spring.io"
          allowedMethods:
            - GET