spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: auth
          uri: ${AUTH_SERVICE}
          predicates:
            - Path=/auth/**
        - id: document-manipulation
          uri: ${DOCUMENT_MANIPULATION_SERVICE}
          filters:
            - AuthGatewayFilter
          predicates:
            - Path=/document/**
        - id: notifications
          uri: ${NOTIFICATIONS_SERVICE}
          filters:
            - AuthGatewayFilter
          predicates:
            - Path=/notifications/**
        - id: users
          uri: ${USERS_SERVICE}
          filters:
            - AuthGatewayFilter
          predicates:
            - Path=/users/**
server:
  port: 8080

cloud:
  gateway:
    globalcors:
      corsConfigurations:
        '[/**]':
          allowedOrigins: "https://docs.spring.io"
          allowedMethods:
            - GET