apiVersion: v1
kind: Service
metadata:
  name: notifications
  namespace: document-collaboration
spec:
  selector:
    app: notifications
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080