services:
  postgres:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "users-db"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
  auth:
    depends_on: [ postgres ]
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      DB_HOST: "localhost"
      DB_PORT: "5432"
      DB: "users-db"
      DB_USER: "root"
      DB_PASSWORD: "root"
      SECRET: "NDA0RTYzNTI2NjU1NkE1ODZFMzI3MjM1NzUzODc4MkY0MTNGNDQyODQ3MkI0QjYyNTA2NDUzNjc1NjZCNTk3MAoa"