spring:
  application:
    name: document-manipulation-service
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: root
      database: collaborative-document
      authentication-database: admin
  kafka:
    bootstrap-servers: localhost:9092