spring:
  application:
    name: document-manipulation-service
  data:
    mongodb:
      host: ${HOST}
      port: ${PORT}
      username: ${USERNAME}
      password: ${PASSWORD}
      database: ${DB}
      authentication-database: ${AUTHENTICATION_DATABASE}
  kafka:
    bootstrap-servers: ${KAFKA}