#spring:
#  application:
#    name: auth-service
#  datasource:
#    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB}
#    username: ${DB_USER}
#    password: ${DB_PASSWORD}
#    driverClassName: org.postgresql.Driver
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#application:
#  security:
#    jwt:
#      secret-key: ${SECRET}
#      expiration: 3000000
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/users-db
    username: root
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
application:
  security:
    jwt:
      secret-key: NDA0RTYzNTI2NjU1NkE1ODZFMzI3MjM1NzUzODc4MkY0MTNGNDQyODQ3MkI0QjYyNTA2NDUzNjc1NjZCNTk3MAoa
      expiration: 3000000
