eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      default-zone: http://localhost:8761/eureka
server:
  port: 0
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: root
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 3000000
