apiVersion: v1
kind: Service
metadata:
  name: documents-content-db
  namespace: document-collaboration
spec:
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: documents-content-db