apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: notifications-hpa
  namespace: document-collaboration
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notifications
  targetCPUUtilizationPercentage: 65