apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: document-collaboration
  name: rtc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rtc
  template:
    metadata:
      labels:
        app: rtc
    spec:
      containers:
        - name: rtc
          image: roddevv/rtc
          resources:
            requests:
              memory: "250Mi"
              cpu: "250m"
            limits:
              memory: "750Mi"
              cpu: "750m"
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          env:
            - name: KAFKA
              valueFrom:
                configMapKeyRef:
                  name: services-map
                  key: kafka
          ports:
            - containerPort: 8080
