management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show:
        details: always
spring:
  application:
    name: rtc-service
  kafka:
    bootstrap-servers: ${KAFKA}
