apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: document-content-handler-db-deployment
  namespace: document-collaboration
spec:
  serviceName: document-content-handler-db-service
  replicas: 3
  selector:
    matchLabels:
      app: document-content-handler-db
  volumeClaimTemplates:
    - metadata:
        name: mongo-volume
      spec:
        storageClassName: local-path
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  template:
    metadata:
      labels:
        app: document-content-handler-db
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          command:
            - mongod
            - "--bind_ip_all"
            - "--replSet"
            - rs0
          volumeMounts:
            - mountPath: /data/db
              name: mongo-volume
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: document-content-handler-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: document-content-handler-secret
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: document-content-handler-db-service
spec:
  clusterIP: None
  selector:
    app: document-content-handler-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017