spring:
  application:
    name: document-content-handler
  data:
    mongodb:
      uri: mongodb://${USERNAME}:${PASSWORD}@${R0}:${PORT},${R1}:${PORT},${R2}:${PORT}/${DB}
  kafka:
    bootstrap-servers: ${KAFKA}