apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: document-collaboration
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: roddevv/auth
          resources:
            requests:
              memory: "250Mi"
              cpu: "250m"
            limits:
              memory: "750Mi"
              cpu: "750m"
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 1
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: users-db-config
                  key: host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: users-db-config
                  key: port
            - name: DB
              valueFrom:
                configMapKeyRef:
                  name: users-db-config
                  key: db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: users-db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: users-db-secret
                  key: password
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: secret-key
          ports:
            - containerPort: 8080