apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: document-collaboration
spec:
  type: NodePort
  selector:
    app: auth
  ports:
    - protocol: TCP
      nodePort: 30001
      port: 80
      targetPort: 8080