apiVersion: apps/v1
kind: Deployment
metadata:
  name: documents-content
  namespace: document-collaboration
spec:
  replicas: 2
  selector:
    matchLabels:
      app: document-content
  template:
    metadata:
      labels:
        app: document-content
    spec:
      containers:
        - name: document-content
          image: roddevv/document-content-handler
          resources:
            requests:
              memory: "250Mi"
              cpu: "250m"
            limits:
              memory: "750Mi"
              cpu: "750m"
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 1
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          env:
            - name: R0
              valueFrom:
                configMapKeyRef:
                  name: documents-content-db-config
                  key: r0
            - name: R1
              valueFrom:
                configMapKeyRef:
                  name: documents-content-db-config
                  key: r1
            - name: R2
              valueFrom:
                configMapKeyRef:
                  name: documents-content-db-config
                  key: r2
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: documents-content-db-config
                  key: port
            - name: DB
              valueFrom:
                configMapKeyRef:
                  name: documents-content-db-config
                  key: db
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: documents-content-db-secret
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: documents-content-db-secret
                  key: password
            - name: KAFKA
              valueFrom:
                configMapKeyRef:
                  name: services-map
                  key: kafka
          ports:
            - containerPort: 8080