apiVersion: v1
kind: Service
metadata:
  name: documents-content
  namespace: document-collaboration
spec:
  selector:
    app: document-content
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
