version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
  document-content-handler:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      CONTENT_DB_HOST: "localhost"
      CONTENT_DB_PORT: "27017"
      CONTENT_DB: "documents_content"
    depends_on:
      - mongodb
