apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: registry.digitalocean.com/document-collaboration/auth
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: user-db-config
                  key: host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: user-db-config
                  key: port
            - name: DB
              valueFrom:
                configMapKeyRef:
                  name: user-db-config
                  key: db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: password
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: secret-key
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080