apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-manipulation-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: document-manipulation
  template:
    metadata:
      labels:
        app: document-manipulation
    spec:
      containers:
        - name: document
          image: roddevv/document-manipulation
          env:
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: document-manipulation-db-config
                  key: host
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: document-manipulation-db-config
                  key: port
            - name: DB
              valueFrom:
                configMapKeyRef:
                  name: document-manipulation-db-config
                  key: db
            - name: AUTHENTICATION_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: document-manipulation-db-config
                  key: authentication-database
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: document-manipulation-secret
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: document-manipulation-secret
                  key: password
            - name: KAFKA
              valueFrom:
                configMapKeyRef:
                  name: services-map
                  key: kafka
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: document-manipulation-service
spec:
  type: NodePort
  selector:
    app: document-manipulation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31000