apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
        - name: notifications
          image: registry.digitalocean.com/document-collaboration/notifications
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: notifications-db-config
                  key: host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: notifications-db-config
                  key: port
            - name: DB
              valueFrom:
                configMapKeyRef:
                  name: notifications-db-config
                  key: db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: notifications-db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notifications-db-secret
                  key: password
            - name: KAFKA
              valueFrom:
                configMapKeyRef:
                  name: services-map
                  key: kafka
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: notifications-service
spec:
  selector:
    app: notifications
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
