apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: document-collaboration
  name: rtc-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rtc
  template:
    metadata:
      labels:
        app: rtc
    spec:
      containers:
        - name: rtc
          image: roddevv/rtc
          env:
            - name: KAFKA
              valueFrom:
                configMapKeyRef:
                  name: services-map
                  key: kafka
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: rtc-service
spec:
  selector:
    app: rtc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
