apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: roddevv/users
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: user-db-config
                  key: host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: user-db-config
                  key: port
            - name: DB
              valueFrom:
                configMapKeyRef:
                  name: user-db-config
                  key: db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: password
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  type: NodePort
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30001