eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      default-zone: http://localhost:8761/eureka
server:
  port: 0
spring:
  application:
    name: users-service
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: root
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update