server:
  port: 0
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: root
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: notifications-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notifications-consumer
    producer:
      group-id: notifications-producer