apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: standard-pvc
  namespace: document-collaboration
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-storage-class
  resources:
    requests:
      storage: 1Gi
