apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: users-db
  namespace: document-collaboration
spec:
  volumeClaimTemplates:
    - metadata:
        name: users-db
      spec:
        storageClassName: standard-storage-class
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  replicas: 1
  selector:
    matchLabels:
      app: users-db
  template:
    metadata:
      labels:
        app: users-db
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: users-db-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: users-db-secret
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: users-db-config
                  key: db
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: users-db
              mountPath: /var/lib/postgresql/data
              subPath: postgres