name: Build API Gateway service
on:
  push:
    paths:
      - api-gateway/**
jobs:
  build-api-gateway:
    runs-on: ubuntu-latest
    name: Build the API Gateway microservice
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
      - run: cd api-gateway && ./mvnw clean && ./mvnw native:compile -Pnative

      - uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          cd api-gateway
          docker build -t roddevv/api-gateway .
          docker push roddevv/api-gateway