name: Build Auth service
on:
  push:
    paths:
      - auth/**
jobs:
  build-api-gateway:
    runs-on: ubuntu-latest
    name: Build the Auth microservice
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '20'
      - run: cd auth && mvn clean && mvn install

      - uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          cd auth
          docker build -t my-dockerhub-user/auth-service:latest .
          docker push my-dockerhub-user/auth-service:latest