name: build-services
on: [ push ]
jobs:
  build-api-gateway:
    runs-on: ubuntu-latest
    name: Build the API Gateway microservice
    steps:
      - uses: docker/login-action@v3
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '20'
      - run: cd api-gateway
      - run: mvn clean
      - run: mvn install
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        name: Build and push API Gateway image
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/document-collaboration-api-gateway:latest