name: build-services
on: [ push ]
jobs:
  build-api-gateway:
    runs-on: ubuntu-latest
    name: Build the API Gateway microservice
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '20'
      - run: cd api-gateway