name: Build RTC service
on:
  push:
    paths:
      - real-time/**
jobs:
  build-notifications:
    runs-on: ubuntu-latest
    name: Build the RTC microservice
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '20'
      - run: cd real-time && mvn clean && mvn install

      - uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          cd real-time
          docker build -t roddevv/rtc .
          docker push roddevv/rtc