name: Build Users service
on:
  push:
    paths:
      - users/**
jobs:
  build-api-gateway:
    runs-on: ubuntu-latest
    name: Build the Users microservice
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '20'
      - run: cd users && mvn clean && mvn install